// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjqKaqluKqLyJpUb-x3FFCidHh-TGKp8w',
    appId: '1:151309273198:web:b7c9eabf8e586608c6be7f',
    messagingSenderId: '151309273198',
    projectId: 'mystore-db-71950',
    authDomain: 'mystore-db-71950.firebaseapp.com',
    storageBucket: 'mystore-db-71950.firebasestorage.app',
    measurementId: 'G-GPXPNTV9JX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp-WmegDoZy0PdmNTFWjnCUeFE0FhTcBU',
    appId: '1:151309273198:android:b98579b2f771fe7ec6be7f',
    messagingSenderId: '151309273198',
    projectId: 'mystore-db-71950',
    storageBucket: 'mystore-db-71950.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKAec8PjMmQOXElJJYkce0IQR6IvdiuJA',
    appId: '1:151309273198:ios:07f4656e36e95f03c6be7f',
    messagingSenderId: '151309273198',
    projectId: 'mystore-db-71950',
    storageBucket: 'mystore-db-71950.firebasestorage.app',
    iosBundleId: 'com.example.mystore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKAec8PjMmQOXElJJYkce0IQR6IvdiuJA',
    appId: '1:151309273198:ios:07f4656e36e95f03c6be7f',
    messagingSenderId: '151309273198',
    projectId: 'mystore-db-71950',
    storageBucket: 'mystore-db-71950.firebasestorage.app',
    iosBundleId: 'com.example.mystore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjqKaqluKqLyJpUb-x3FFCidHh-TGKp8w',
    appId: '1:151309273198:web:3341b23fc1e4fd11c6be7f',
    messagingSenderId: '151309273198',
    projectId: 'mystore-db-71950',
    authDomain: 'mystore-db-71950.firebaseapp.com',
    storageBucket: 'mystore-db-71950.firebasestorage.app',
    measurementId: 'G-2DB0K1ELN8',
  );
}
